[package]
name = "codegen-test-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
ir.workspace = true
codegen.workspace = true

cranelift-entity.workspace = true
anyhow.workspace = true
capstone.workspace = true
itertools.workspace = true

libc = "0.2.158"
