[package]
name = "ir-graphviz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ir.workspace = true

[dev-dependencies]
expect-test.workspace = true
