on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
      - run: cargo check --all-features

  test:
    name: Rust Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
      - run: cargo test --all-features

  filetest:
    name: File Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
      - run: cargo filetest

  test-c-api:
    name: C API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
        with:
          targets: x86_64-unknown-none
      - run: c-api-tests/run.sh

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
        with:
          components: clippy
      - run: cargo clippy --all-features -- -D warnings

  clippy-c-api-unlogged:
    name: Clippy (C API, Logging disabled)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
        with:
          components: clippy
          targets: x86_64-unknown-none
      - run: cargo clippy -p c-api --features no_logging --target x86_64-unknown-none -- -D warnings

  clippy-c-api-logged:
    name: Clippy (C API, Logging enabled)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.84
        with:
          components: clippy
          targets: x86_64-unknown-none
      - run: cargo clippy -p c-api --target x86_64-unknown-none -- -D warnings
